name: LocalLift CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run env check
        run: |
          python tools/env_check.py

      - name: Start server test
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 &
          sleep 5
